"""Parser and validator for exercises generated by LLM."""
import json
import re

def parse_exercises(raw_content: str, vocab_ids: list[str] | None = None) -> list[dict]:
    """Extract and validate exercise objects from raw LLM output."""

    text = (raw_content or "").strip()

    # Try to find JSON array in the output
    m = re.search(r"\[[\s\S]*\]", text)
    if not m:
        return []

    try:
        data = json.loads(m.group())
        if not isinstance(data, list):
            return []

        valid_exercises = []
        for item in data:
            if not isinstance(item, dict):
                continue

            # Basic validation
            if not all(k in item for k in ("type", "prompt", "answer")):
                continue

            # Filter by valid types
            if item["type"] not in ("fill_blank", "translation", "char_recognition", "sentence_construction"):
                continue

            # Clean up the object
            clean_item = {
                "type": item["type"],
                "prompt": str(item["prompt"]),
                "answer": str(item["answer"]),
                "options": item.get("options") if isinstance(item.get("options"), list) else None,
                "hint": str(item["hint"]) if item.get("hint") else None,
                "vocab_id": str(item["vocab_id"]) if item.get("vocab_id") else None
            }

            # Optionally validate vocab_id if list of allowed IDs was provided
            if vocab_ids and clean_item["vocab_id"] not in vocab_ids:
                # If we have vocab_ids but it's not in them, we can either skip it or keep it.
                # Since the LLM might have used its own knowledge, we'll keep it but set vocab_id to None if invalid.
                clean_item["vocab_id"] = None

            valid_exercises.append(clean_item)

        return valid_exercises

    except json.JSONDecodeError:
        return []
